### ISSUE TITLE
Support for reviewer link in database (impossible to remember hash)

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#244]

**Comment by viklund** [comment]
Suggested implementation:

A new database table called `hash` with 4 columns (`hash_id`, `dataset_file_id`, `hash`, `expirydate`).

A python controller that catches requests to some route, for example `/private-files/<hash>` and then reroutes that to the nginx frontend similar to how the AuthorizedStaticNginxFileHandler does it.

Possibly we should link the `hash` table to `dataset_version` instead of `dataset_file` to get links to all files in a dataset instead.
