### ISSUE TITLE
About swefreq på swefreq.nbis.se/

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#41]

**Comment by nicjar** [comment]
The Swedish Frequency resource for genomics (SweFreq) is a website developed to make genomic datasets more findable and accessible in order to promote collaboration, new research and increase public benefit. You can contact swefreq@scilifelab.se if you want to find out more about this resource and how it could benefit you and your research.

**Comment by nicjar** [comment]
swegen@scilifelab.se - for questions, comments, etc., regarding the SweGen cohort dataset.

**Comment by kusalananda** [comment]
Too soon.
